version: '3.8'

services:
  villainary-react:
    build:
      context: ./villainary-react
      target: runner
      dockerfile: Dockerfile
    volumes:
      - ./villainary-react:/app/villainary-react
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
